### ISSUE TITLE
Feral Rotation pops error/stops

### ISSUE THREAD

**Issue by hgdubbe** [adde88/Nerdpack-Zylla#11]
feral rotation pops following error and stops almost every fight:
https://pastebin.com/gBZjqUV2

caused by the lines
```
NeP.DSL:Register('dot.pmultiplier', function(_, spell)
  return Zylla.f_Snapshots[spell:lower()][UnitGUID('target')] or 0
end)

NeP.DSL:Register('persistent_multiplier', function(_, spell)
  return Zylla.f_Snapshots[spell:lower()].current or 1
end)
```
seems to happen after fast target switching or manual interference 

edit: nope, also happens with no interference
dumping f_test always returns table containing the dots names but no content

**Comment by adde88** [comment]
Interesting. I'll take a look at into today.

**Comment by adde88** [comment]
Testing Feral here. Dumping **f_test** is working here.


Could you try this? : **/dump Zylla.f_Snapshots**

**Comment by adde88** [comment]
Btw, i read the error message.
Have you updated lately? Like within the last days?
I recently updated these conditions-
Also i tried going to line 539 in my conditions.lua file, and it provides me something else than the one you are running.

**Comment by hgdubbe** [comment]
at the time of creation it was the latest version, cant test atm as the whole addon doesnt work for me with the latest changes ;)

**Comment by hgdubbe** [comment]
/dump Zylla.f_Snapshots returns [link](https://pastebin.com/Q8Na77LB) after the rotation stops.
the error thrown into bugsack reads [link](https://pastebin.com/0NQKZWt4)

tested it several times, the error always appears after the first regrowth [nerdpack action log](https://ibb.co/ju39qb)

unlocker is firehack
everything updated with nerdpack toolbox

**Comment by adde88** [comment]
Can you check if this is still an issue for you?

**Comment by hgdubbe** [comment]
got hit by the last banwave, so i can't test it, sorry :-/
