### ISSUE TITLE
Balance druid

### ISSUE THREAD

**Issue by Atnaszurc** [adde88/Nerdpack-Zylla#13]
Profile gets stuck at pooling for Starsurge, won't cast anything while waiting. 
@Zurc in the discord channel.

![image](https://user-images.githubusercontent.com/32467110/31096140-7ecde18a-a7bb-11e7-8790-e965c9738b89.png)

**Comment by adde88** [comment]
Will look into it.
Pooling = Waiting for resources, because there's nothing else to do atm (according to the CR)
So if you have any idea what it should rather be doing at that moment, post it here, so i can try tweaking the CR.

**Comment by adde88** [comment]
Still an issue?

**Comment by Atnaszurc** [comment]
Sorry for the late reply. The update you released straight after fixed the problem.
