### ISSUE TITLE
Getting Lua errors on DH

### ISSUE THREAD

**Issue by Jefferyasbell** [adde88/Nerdpack-Zylla#22]
5x Nerdpack-Zylla\actions.lua:29: attempt to index field 'Actions' (a nil value)
Nerdpack-Zylla\actions.lua:29: in main chunk

Locals:
_ = "Nerdpack-Zylla"
NeP = <table> {
 f_update = <function> defined @Nerdpack-Zylla\core.lua:591
 AutoDoT = <function> defined @Nerdpack-Zylla\core.lua:97
 UnitDot = <function> defined @Nerdpack-Zylla\core.lua:212
 f_cp = 0
 Blacklist = <table> {
 }
 Scan_IgnorePain = <function> defined @Nerdpack-Zylla\core.lua:168
 Donate = <function> defined @Nerdpack-Zylla\core.lua:59
 prepots = <table> {
 }
 f_events = <table> {
 }
 nep_ver = "1.11"
 Author = "Zylla"
 spell_timers = <table> {
 }
 Voidform_Summary = true
 f_updateDmg = <function> defined @Nerdpack-Zylla\core.lua:607
 TravelTime = <function> defined @Nerdpack-Zylla\core.lua:676
 KilJaedenTrinket = <table> {
 }
 dynEval = <function> defined @Nerdpack-Zylla\core.lua:699
 Branch = "RELEASE"
 SpellIDs = <table> {
 }
 f_debuffID = <table> {
 }
 PetMode = 0
 ShortNumber = <function> defined @Nerdpack-Zylla\core.lua:72
 ExeOnLoad = <function> defined @Nerdpack-Zylla\core.lua:42
 setsTable = <table> {
 }
 isAFK = false
 GetPredictedHealth = <function> defined @Nerdpack-Zylla\core.lua:703
 getIgnorePain = <function> defined @Nerdpack-Zylla\core.lua:230
 Logo_GUI = <table> {
 }
 Version = "2.6"
 AutoDoT2 = <function> defined @Nerdpack-Zylla\core.lua:129
 AFKCheck = <function> defined @Nerdpack-Zylla\core.lua:36
 S2M_Summary = true
 Overlay = <unnamed> {
 }
 PaidCR_GUI = <table> {
 }
 pets = <table> {
 }
 wow_ver = "7.3.2"
 addonColor = "8801C0"
 GuiSettings = <table> {
 }
 f_lastUpdate = 0
 ClassColor = "|cffFFFFFF"
 timer = <table> {
 }
 f_cancelCleanUp = <function> defined @Nerdpack-Zylla\core.lua:647
 faketarget = <table> {
 }
 SA_Cleanup = <function> defined @Nerdpack-Zylla\core.lua:511
 f_Snapshots = <table> {
 }
 f_buffID = <table> {
 }
 flySpells = <table> {
 }
 Mythic_Plus = <table> {
 }
 GetNumberSetPieces = <function> defined @Nerdpack-Zylla\core.lua:491
 UnitHot = <function> defined @Nerdpack-Zylla\core.lua:197
 Mythic_GUI = <table> {
 }
 Round = <function> defined @Nerdpack-Zylla\core.lua:63
 f_cleanUp = <function> defined @Nerdpack-Zylla\core.lua:630
 PayPal_GUI = <table> {
 }
 PayPal_IMG = <table> {
 }
 ts = <function> defined @Nerdpack-Zylla\core.lua:726
 ChatOverlay = <function> defined @Nerdpack-Zylla\overlay.lua:26
 Splash = <function> defined @Nerdpack-Zylla\splash.lua:41
 tt = <function> defined @Nerdpack-Zylla\core.lua:720
 onFlagChange = <function> defined @Nerdpack-Zylla\core.lua:18
 NrHealsAroundFriendly = <function> defined @Nerdpack-Zylla\core.lua:707
 Travel_Times = <table> {
 }
 ExeOnUnload = <function> defined @Nerdpack-Zylla\core.lua:55
 DonateURL = "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=23HX4QKDAD4YG"
 Class = 12
 Name = "NerdPack - Zylla's Rotations"
 f_buffs = <table> {
 }
 Scan_SpellCost = <function> defined @Nerdpack-Zylla\core.lua:156
 wpets = <table> {
 }
 f_strings = <table> {
 }
}
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 NePDATA = <table> {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 734
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 394
 RecruitAFriendFrame = Re

**Comment by Jefferyasbell** [comment]
The above error persists thru all my characters sorry for previous post where AI said it was just DH.

**Comment by adde88** [comment]
I think i know whatms causing it.
Will check it asap. when i have time :)

**Comment by adde88** [comment]
Fixed in latest commit.
