### ISSUE TITLE
DH Broken

### ISSUE THREAD

**Issue by Jefferyasbell** [adde88/Nerdpack-Zylla#24]
Since the last release DH Havoc is not working anymore can use MTS rotations but Zylla will not go into CR Bummer

**Comment by adde88** [comment]
Any more info?
Not working at all? Or partially working?

**Comment by Jefferyasbell** [comment]
All I get in the actions log is stopcasting over and over again. It got to 350 b4 I stoped hitting dummies by backing away with auto attack and it will not work at all I dissabled all my addons cept NEep addons and Zylla I downloaded it with the toolbox for Nep. so it is the latest release. Since I downloaded that It broke the CR for DH

**Comment by adde88** [comment]
Stopcasting in the Action Log? What in....
No where in my Havoc CR is it specified to use /stopcasting. This is vary strange.
I'll look into it asap.

**Comment by adde88** [comment]
Found the issue. It should be fixed in the latest commits. :)
