### ISSUE TITLE
Feral Druid getting lua errors

### ISSUE THREAD

**Issue by Jefferyasbell** [adde88/Nerdpack-Zylla#25]
1x NerdPack-Trip\conditions.lua:182: attempt to call field 'UnitDot' (a nil value)
NerdPack-Trip\conditions.lua:182: in function <NerdPack-Trip\conditions.lua:181>
NerdPack\system\dsl.lua:113: in function <NerdPack\system\dsl.lua:89>
(tail call): ?
NerdPack\system\dsl.lua:141: in function <NerdPack\system\dsl.lua:137>
(tail call): ?
NerdPack\system\dsl.lua:132: in function <NerdPack\system\dsl.lua:119>
(tail call): ?
NerdPack\system\dsl.lua:47: in function <NerdPack\system\dsl.lua:45>
(tail call): ?
NerdPack\system\parser.lua:119: in function `func'
NerdPack\system\parser.lua:101: in function <NerdPack\system\parser.lua:93>
(tail call): ?
NerdPack\system\parser.lua:111: in function `func'
NerdPack\system\parser.lua:101: in function <NerdPack\system\parser.lua:93>
(tail call): ?
NerdPack\system\parser.lua:111: in function `func'
NerdPack\system\parser.lua:101: in function <NerdPack\system\parser.lua:93>
(tail call): ?
NerdPack\system\parser.lua:195: in function <NerdPack\system\parser.lua:180>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
InCombatSkipped

**Comment by adde88** [comment]
The error is not caused by my AddOn.
If you read the error-message you'll notice: **NerdPack-Trip**
Seems to be having an issue with: **conditions.lua** at line 181.

Trip has to fix this problem, or his AddOn has to be disabled to avoid this error.

**Comment by Jefferyasbell** [comment]
TY for that info I thought I had disabled it but I guess it was not disabled it. thank you for info. Im new at reading Lua errors so sorry
