### ISSUE TITLE
Little issue with paladin rotation

### ISSUE THREAD

**Issue by br4bit** [adde88/Nerdpack-Zylla#5]
Hi, i don't know if it's an issue but when Judgement is on CD and Target hasn't a judgement debuff the bot will wait until judgement cd ends...maybe he should use other spell like crusader or zeal...

ty 📦

top 💃

**Comment by adde88** [comment]
Just to clarify, are you playing Retribution spec?
And do you mean that the rotation does nothing while it waits for Judgment to become ready again?
sorry for being so specific, but it really helps debugging these routines having as much information as possible.

**Comment by adde88** [comment]
I've re-written huge parts of the Retribution CR.
I noticed some small errors, like the old OP's still being used. Let me know if it's still buggy for you.

**Comment by br4bit** [comment]
Yes retri rotations...sorry for my english XD i try to explain scenario:

1. Target First enemy/mob: Use judgement->ecc...
2. Target Second enemy/mob: no spells until judgement cd ends....after Judgement is available it will start again...

It would be nice to add HoF while you're snared or rooted..like yumad rotations:

https://github.com/damuY/NerdPack-Yumad/blob/master/rotations/paladin/retribution.lua

ty 👍

**Comment by adde88** [comment]
This issue should be resolved after the latest updates.
