### ISSUE TITLE
windwalker rotation not working

### ISSUE THREAD

**Issue by mujw** [adde88/Nerdpack-Zylla#6]
windwalker monk rotation not work for me, when I start fighting the trinket will use automatically and then do nothing.

**Comment by adde88** [comment]
I'm sorry it has issues, Windwalker is one of my top-performing routines.
I'll take a look asap. Hopefully today.
Going over a lot of stuff on all combat-routines at the moment.
Thanks for the feedback!

**Comment by adde88** [comment]
Ok. I just tested the latest Windwalker rotation. And it works perfectly for me.
I'm not sure why you are having problems.
Make sure you are running the latest version of NerdPack, all of it's modules, and my addon.
Are you using an advanced unlocker? Are you having problems with any other rotations?

**Comment by adde88** [comment]
I'm closing this issue, as i'm certain that the routine is working correctly.

**Comment by mujw** [comment]
yes I use andvanced unlocker.

I reinstalled all nerdpack and rotation and still not work and when I try to use the core model, after I cast

 some spells it show this message




Message: Interface\AddOns\NerdPack\system\lib.lua:28: attempt to call field '?' (a nil value)
Time: 08/04/17 08:05:24
Count: 1
Stack: Interface\AddOns\NerdPack\system\lib.lua:28: attempt to call field '?' (a nil value)Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: in function `?'
Interface\AddOns\NerdPack\system\lib.lua:28: in function <Interface\AddOns\NerdPack\system\lib.lua:20>
(tail call): ?
(tail call): ?
Interface\AddOns\NerdPack\system\dsl.lua:48: in function <Interface\AddOns\NerdPack\system\dsl.lua:43>
(tail call): ?
Interface\AddOns\NerdPack\system\dsl.lua:45: in function <Interface\AddOns\NerdPack\system\dsl.lua:43>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:104: in function `func'
Interface\AddOns\NerdPack\system\parser.lua:96: in function <Interface\AddOns\NerdPack\system\parser.lua:87>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:106: in function `func'
Interface\AddOns\NerdPack\system\parser.lua:96: in function <Interface\AddOns\NerdPack\system\parser.lua:87>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:151: in function <Interface\AddOns\NerdPack\system\parser.lua:141>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: errorMessage = "Interface\AddOns\NerdPack\system\lib.lua:28: attempt to call field '?' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0


any idea? thx

**Comment by adde88** [comment]
I can't see to find any references to my routine within that error message, so it seems like something is happening with NerdPack itself.
I suggest you report this error to MrTheSoulz, or post it to NerdPack's core repository.

I'm also curious, what language is your wow-client running? There have been issues in the past with some other locales.
